apiVersion: {{ .metadata.apiVersion }}
kind: Ingress
metadata:
  name: {{ .metadata.name }}
  namespace: {{ .metadata.namespace }}
  {{- if .metadata.labels }}
  labels:
    {{- include "common.labelSlice2Map" .metadata.labels | indent 4 }}
  {{- end }}
  annotations:
    {{- range .metadata.annotations }}
    {{- if and (ne .key "kubernetes.io/ingress.class") (ne .key "kubernetes.io/ingress.existLbId") (ne .key "ingress.cloud.tencent.com/pass-to-target") (ne .key "kubernetes.io/ingress.subnetId") }}
    {{ .key | quote }}: {{ .value | default "" | quote }}
    {{- end }}
    {{- end }}
    {{- if .controller.type }}
    kubernetes.io/ingress.class: {{ .controller.type | quote }}
    {{- end }}
    # 处理 qcloud 特有的一些 annotations
    {{- if eq .controller.type "qcloud" }}
    {{- if eq .spec.network.clbUseType "useExists" }}
    kubernetes.io/ingress.existLbId: {{ .spec.network.existLBID | quote }}
    {{- else }}
    {{- if and (.spec.network.subNetID) (eq .spec.network.clbType "internal") }}
    kubernetes.io/ingress.subnetId: {{ .spec.network.subNetID | quote }}
    {{- end }}
    ingress.cloud.tencent.com/pass-to-target: "true"
    {{- end }}
    {{- end }}
spec:
  {{- if and .spec.defaultBackend.targetSVC .spec.defaultBackend.port }}
  defaultBackend:
    {{- include "network.ingress.backend" (dict "svcName" .spec.defaultBackend.targetSVC "svcPort" .spec.defaultBackend.port "apiVersion" .metadata.apiVersion) | nindent 4 }}
  {{- end }}
  {{- if .spec.cert.tls }}
  tls:
    {{- range .spec.cert.tls }}
    - secretName: {{ .secretName }}
      {{- if .hosts }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .spec.ruleConf.rules }}
    - http:
        paths:
          {{- range .paths }}
          - backend:
              {{- include "network.ingress.backend" (dict "svcName" .targetSVC "svcPort" .port "apiVersion" $.metadata.apiVersion ) | nindent 14 }}
            path: {{ .path | quote }}
            # v1 版本才支持 pathType
            {{- if and (eq $.metadata.apiVersion "networking.k8s.io/v1") .type }}
            pathType: {{ .type }}
            {{- end }}
          {{- end }}
      host: {{ .domain | quote }}
    {{- end }}
