{{ include "common.metadata" . }}
- - group:
      - - group:
            - [ "key", "value", "." ]
          prop: items
          container:
            grid-template-columns: "1fr 1fr 60px"
    prop: data
